
package aganaktish;

import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**Ylopoiei to parathyriko perivallon epikoinwnias me ton xrhsth.
 * 
 * @author Panos
 */

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectCollectionDialog = new javax.swing.JDialog();
        selectCollectionBox = new javax.swing.JComboBox();
        dialogOkButton = new javax.swing.JButton();
        openCollectionCancelButton = new javax.swing.JButton();
        createCollectionDialog = new javax.swing.JDialog();
        pathTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        createOkCollectionButton = new javax.swing.JButton();
        dialogCancelButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        boolORvectorDialog = new javax.swing.JDialog();
        currentCollectionLabel = new javax.swing.JLabel();
        useBooleanButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        editCollectionButton = new javax.swing.JButton();
        useRecallCalcButton = new javax.swing.JButton();
        boolORvectorWarningLabel = new javax.swing.JLabel();
        booleanWindow = new javax.swing.JDialog();
        queryBoolTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        booleanSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booleanResultTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        booleanCancelButton = new javax.swing.JButton();
        booleanWarning = new javax.swing.JLabel();
        vectorWindow = new javax.swing.JDialog();
        queryVectorTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vectorSearchButton = new javax.swing.JButton();
        vectorCancelButton = new javax.swing.JButton();
        vectorWarning = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vectorResultTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        vectorMethodComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        topKTextField = new javax.swing.JTextField();
        editCollectionWindow = new javax.swing.JDialog();
        addtxtSourcePathTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addTxtButton = new javax.swing.JButton();
        addTxtWarning = new javax.swing.JLabel();
        deleteTxtButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deleteSelectedList = new javax.swing.JList();
        editGoBackButton = new javax.swing.JButton();
        removeCommonWordsButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        commonPercentageTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precisionCalcWindow = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        recallResultTextArea = new javax.swing.JTextArea();
        recallTopKTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        recallCalcStartButton = new javax.swing.JButton();
        recallCalcCancelButton = new javax.swing.JButton();
        recallCalcMethodComboBox = new javax.swing.JComboBox();
        openCollectionButton = new javax.swing.JButton();
        createCollectionButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        selectCollectionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        selectCollectionDialog.setTitle("Collections");
        selectCollectionDialog.setBounds(new java.awt.Rectangle(0, 0, 400, 255));
        selectCollectionDialog.setMinimumSize(new java.awt.Dimension(400, 255));

        selectCollectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCollectionBoxActionPerformed(evt);
            }
        });

        dialogOkButton.setText("Select");
        dialogOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogOkButtonActionPerformed(evt);
            }
        });

        openCollectionCancelButton.setText("Cancel");
        openCollectionCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCollectionCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectCollectionDialogLayout = new javax.swing.GroupLayout(selectCollectionDialog.getContentPane());
        selectCollectionDialog.getContentPane().setLayout(selectCollectionDialogLayout);
        selectCollectionDialogLayout.setHorizontalGroup(
            selectCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectCollectionDialogLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(selectCollectionBox, 0, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(selectCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(openCollectionCancelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialogOkButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        selectCollectionDialogLayout.setVerticalGroup(
            selectCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectCollectionDialogLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(selectCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCollectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogOkButton))
                .addGap(18, 18, 18)
                .addComponent(openCollectionCancelButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        createCollectionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        createCollectionDialog.setTitle("New Collection");
        createCollectionDialog.setMinimumSize(new java.awt.Dimension(500, 340));

        jLabel1.setText("Enter the path of the txt");

        jLabel2.setText("Enter the name of the Collection");

        createOkCollectionButton.setText("Create");
        createOkCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOkCollectionButtonActionPerformed(evt);
            }
        });

        dialogCancelButton.setText("Cancel");
        dialogCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCollectionDialogLayout = new javax.swing.GroupLayout(createCollectionDialog.getContentPane());
        createCollectionDialog.getContentPane().setLayout(createCollectionDialogLayout);
        createCollectionDialogLayout.setHorizontalGroup(
            createCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCollectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCollectionDialogLayout.createSequentialGroup()
                .addGroup(createCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createCollectionDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createCollectionDialogLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(createOkCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dialogCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        createCollectionDialogLayout.setVerticalGroup(
            createCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCollectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(pathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(createCollectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createOkCollectionButton)
                    .addComponent(dialogCancelButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        boolORvectorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        boolORvectorDialog.setTitle("Action Selection");
        boolORvectorDialog.setMinimumSize(new java.awt.Dimension(500, 350));

        useBooleanButton.setText("Use Boolean");
        useBooleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useBooleanButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Use Vector");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        editCollectionButton.setText("Edit Collection");
        editCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCollectionButtonActionPerformed(evt);
            }
        });

        useRecallCalcButton.setText("Get Precision/Recall");
        useRecallCalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useRecallCalcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boolORvectorDialogLayout = new javax.swing.GroupLayout(boolORvectorDialog.getContentPane());
        boolORvectorDialog.getContentPane().setLayout(boolORvectorDialogLayout);
        boolORvectorDialogLayout.setHorizontalGroup(
            boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boolORvectorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(useRecallCalcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(useBooleanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackButton))
                .addGap(63, 63, 63))
            .addGroup(boolORvectorDialogLayout.createSequentialGroup()
                .addGroup(boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boolORvectorDialogLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(currentCollectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boolORvectorDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boolORvectorWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        boolORvectorDialogLayout.setVerticalGroup(
            boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boolORvectorDialogLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(currentCollectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useBooleanButton)
                    .addComponent(editCollectionButton))
                .addGap(18, 18, 18)
                .addGroup(boolORvectorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(goBackButton))
                .addGap(18, 18, 18)
                .addComponent(useRecallCalcButton)
                .addGap(30, 30, 30)
                .addComponent(boolORvectorWarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        booleanWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        booleanWindow.setTitle("Boolean Model");
        booleanWindow.setMinimumSize(new java.awt.Dimension(600, 700));

        jLabel3.setText("Query:");

        booleanSearchButton.setText("Search");
        booleanSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanSearchButtonActionPerformed(evt);
            }
        });

        booleanResultTextArea.setColumns(20);
        booleanResultTextArea.setRows(5);
        jScrollPane1.setViewportView(booleanResultTextArea);

        jLabel4.setText("Gagan GAGAN...");

        booleanCancelButton.setText("Cancel");
        booleanCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout booleanWindowLayout = new javax.swing.GroupLayout(booleanWindow.getContentPane());
        booleanWindow.getContentPane().setLayout(booleanWindowLayout);
        booleanWindowLayout.setHorizontalGroup(
            booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(booleanWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(booleanWindowLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(booleanWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(booleanWindowLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(booleanSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(booleanCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(queryBoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        booleanWindowLayout.setVerticalGroup(
            booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanWindowLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryBoolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(booleanWindowLayout.createSequentialGroup()
                        .addGroup(booleanWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booleanCancelButton)
                            .addComponent(booleanSearchButton))
                        .addGap(18, 18, 18)
                        .addComponent(booleanWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
        );

        vectorWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        vectorWindow.setTitle("Vector Model");
        vectorWindow.setMinimumSize(new java.awt.Dimension(600, 700));

        jLabel5.setText("Query:");

        vectorSearchButton.setText("Search");
        vectorSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorSearchButtonActionPerformed(evt);
            }
        });

        vectorCancelButton.setText("Cancel");
        vectorCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorCancelButtonActionPerformed(evt);
            }
        });

        vectorResultTextArea.setColumns(20);
        vectorResultTextArea.setRows(5);
        jScrollPane2.setViewportView(vectorResultTextArea);

        jLabel6.setText("Results:");

        vectorMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cosine Method", "Jaccard Method", "Dice Method" }));

        jLabel7.setText("Return top k:");

        javax.swing.GroupLayout vectorWindowLayout = new javax.swing.GroupLayout(vectorWindow.getContentPane());
        vectorWindow.getContentPane().setLayout(vectorWindowLayout);
        vectorWindowLayout.setHorizontalGroup(
            vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vectorWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vectorWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vectorWindowLayout.createSequentialGroup()
                                .addComponent(vectorSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vectorCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vectorMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vectorWindowLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(topKTextField))
                                .addComponent(vectorWarning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(240, 240, 240))
                    .addGroup(vectorWindowLayout.createSequentialGroup()
                        .addComponent(queryVectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(210, Short.MAX_VALUE))))
        );
        vectorWindowLayout.setVerticalGroup(
            vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vectorWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(queryVectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vectorWindowLayout.createSequentialGroup()
                        .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vectorSearchButton)
                            .addComponent(vectorCancelButton))
                        .addGap(18, 18, 18)
                        .addComponent(vectorMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(vectorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(topKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(vectorWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addContainerGap())
        );

        editCollectionWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        editCollectionWindow.setTitle("Edit Collection");
        editCollectionWindow.setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel8.setText("Give source path:");

        addTxtButton.setText("Add");
        addTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtButtonActionPerformed(evt);
            }
        });

        deleteTxtButton.setText("Delete");
        deleteTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTxtButtonActionPerformed(evt);
            }
        });

        deleteSelectedList.setMaximumSize(new java.awt.Dimension(0, 400));
        jScrollPane3.setViewportView(deleteSelectedList);

        editGoBackButton.setText("Go Back");
        editGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGoBackButtonActionPerformed(evt);
            }
        });

        removeCommonWordsButton.setText("Remove common words");
        removeCommonWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCommonWordsButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Common words are those who exist in more than :");

        jLabel12.setText("%");

        javax.swing.GroupLayout editCollectionWindowLayout = new javax.swing.GroupLayout(editCollectionWindow.getContentPane());
        editCollectionWindow.getContentPane().setLayout(editCollectionWindowLayout);
        editCollectionWindowLayout.setHorizontalGroup(
            editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCollectionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editCollectionWindowLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commonPercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(editCollectionWindowLayout.createSequentialGroup()
                        .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteTxtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCollectionWindowLayout.createSequentialGroup()
                                .addComponent(removeCommonWordsButton)
                                .addContainerGap())
                            .addComponent(addTxtWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editCollectionWindowLayout.createSequentialGroup()
                        .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editCollectionWindowLayout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addTxtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(editGoBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(addtxtSourcePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        editCollectionWindowLayout.setVerticalGroup(
            editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCollectionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(addtxtSourcePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editCollectionWindowLayout.createSequentialGroup()
                        .addComponent(addTxtButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editGoBackButton)
                        .addGap(18, 18, 18)
                        .addComponent(addTxtWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(commonPercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(editCollectionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeCommonWordsButton)
                    .addComponent(deleteTxtButton))
                .addContainerGap())
        );

        jLabel9.setText("jLabel9");

        precisionCalcWindow.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        precisionCalcWindow.setMinimumSize(new java.awt.Dimension(500, 600));

        recallResultTextArea.setColumns(20);
        recallResultTextArea.setRows(5);
        jScrollPane4.setViewportView(recallResultTextArea);

        jLabel13.setText("Top k results:");

        jLabel14.setText("Results:");

        recallCalcStartButton.setText("START");
        recallCalcStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallCalcStartButtonActionPerformed(evt);
            }
        });

        recallCalcCancelButton.setText("Cancel");
        recallCalcCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallCalcCancelButtonActionPerformed(evt);
            }
        });

        recallCalcMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cosine Method", "Dice Method", "Jaccard Method" }));

        javax.swing.GroupLayout precisionCalcWindowLayout = new javax.swing.GroupLayout(precisionCalcWindow.getContentPane());
        precisionCalcWindow.getContentPane().setLayout(precisionCalcWindowLayout);
        precisionCalcWindowLayout.setHorizontalGroup(
            precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, precisionCalcWindowLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recallCalcCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recallCalcStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                                .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(recallTopKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(recallCalcMethodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 33, Short.MAX_VALUE))))))
        );
        precisionCalcWindowLayout.setVerticalGroup(
            precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(precisionCalcWindowLayout.createSequentialGroup()
                        .addGroup(precisionCalcWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recallTopKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(recallCalcMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(recallCalcStartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recallCalcCancelButton)
                        .addGap(29, 29, 29))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information Retrieval Project");

        openCollectionButton.setText("Open Collection");
        openCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCollectionButtonActionPerformed(evt);
            }
        });

        createCollectionButton.setText("CreateCollection");
        createCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCollectionButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Information Retrieval Project CSD AUTH 2012");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(exitButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectCollectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCollectionBoxActionPerformed
    }//GEN-LAST:event_selectCollectionBoxActionPerformed

    private void openCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCollectionButtonActionPerformed
        selectCollectionDialog.setVisible(true);
        this.setState(Frame.ICONIFIED);
        this.setEnabled(false);

        selectCollectionBox.removeAllItems();
        for (String temp : Aganaktish.Sylloges) {
            selectCollectionBox.addItem(temp);
        }
    }//GEN-LAST:event_openCollectionButtonActionPerformed

    private void dialogOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogOkButtonActionPerformed
        String tempString = selectCollectionBox.getSelectedItem().toString();
        try {
            CollectionClass.openCollection(tempString);
            selectCollectionDialog.setVisible(false);
            boolORvectorDialog.setVisible(true);

            String tempStr = Aganaktish.collectionPath;
            tempStr = tempStr.substring(tempStr.lastIndexOf("\\") + 1, tempStr.length());
            currentCollectionLabel.setText(tempStr);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        selectCollectionDialog.setAlwaysOnTop(false);
        selectCollectionDialog.setVisible(false);
        //GOTO NEW WINDOW Vector, Boolean

    }//GEN-LAST:event_dialogOkButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            CollectionClass.closeCollection();
            System.exit(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void createOkCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOkCollectionButtonActionPerformed


        try {
            if (pathTxtField.getText().equals("") || nameTextField.getText().equals("")) {
                warningLabel.setText("Please fill the form");
            } else {

                CollectionClass.createCollection(pathTxtField.getText(), nameTextField.getText());
                warningLabel.setText("");
                createCollectionDialog.setVisible(false);
                this.setState(Frame.ICONIFIED);
                this.setEnabled(true);


            }
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createOkCollectionButtonActionPerformed

    private void dialogCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogCancelButtonActionPerformed
        createCollectionDialog.setVisible(false);
        this.setState(Frame.NORMAL);
        this.setEnabled(true);
    }//GEN-LAST:event_dialogCancelButtonActionPerformed

    private void createCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCollectionButtonActionPerformed
        createCollectionDialog.setVisible(true);
        this.setState(Frame.ICONIFIED);
        this.setEnabled(false);

    }//GEN-LAST:event_createCollectionButtonActionPerformed

    private void openCollectionCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCollectionCancelButtonActionPerformed
        selectCollectionDialog.setVisible(false);
        this.setState(Frame.NORMAL);
        this.setEnabled(true);
    }//GEN-LAST:event_openCollectionCancelButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        boolORvectorDialog.setVisible(false);
        selectCollectionDialog.setVisible(true);
        selectCollectionBox.removeAllItems();
        boolORvectorWarningLabel.setText("");
        try {
            CollectionClass.closeCollection();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String temp : Aganaktish.Sylloges) {
            selectCollectionBox.addItem(temp);
        }
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void useBooleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useBooleanButtonActionPerformed
        boolORvectorDialog.setVisible(false);
        booleanWindow.setVisible(true);
    }//GEN-LAST:event_useBooleanButtonActionPerformed

    private void booleanCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanCancelButtonActionPerformed
        booleanWindow.setVisible(false);
        boolORvectorDialog.setVisible(true);
        booleanResultTextArea.setText("");
        queryBoolTextField.setText("");
        booleanWarning.setText("");
    }//GEN-LAST:event_booleanCancelButtonActionPerformed

    private void booleanSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanSearchButtonActionPerformed

        if (queryBoolTextField.getText().equals("")) {
            booleanWarning.setText("Please insert a query");
        } else {
            String query = queryBoolTextField.getText();
            ArrayList<String> myList = Boolean.searchBooleanQuery(query);
            String result = "";
            if (myList.isEmpty()) {
                booleanResultTextArea.setText("No results found");
            } else {
                Collections.sort(myList);
                for (String temp : myList) {

                    result = result + temp + "\n";
                }
                booleanResultTextArea.setText(result);
            }
        }



    }//GEN-LAST:event_booleanSearchButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolORvectorDialog.setVisible(false);
        vectorWindow.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void vectorCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorCancelButtonActionPerformed
        vectorWindow.setVisible(false);
        boolORvectorDialog.setVisible(true);
        vectorResultTextArea.setText("");
        queryVectorTextField.setText("");
        vectorWarning.setText("");
        topKTextField.setText("");
    }//GEN-LAST:event_vectorCancelButtonActionPerformed

    private void vectorSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorSearchButtonActionPerformed


        if (queryVectorTextField.getText().equals("")) {
            vectorWarning.setText("Please insert a query");
        } else {
            String query = queryVectorTextField.getText();
            String method = vectorMethodComboBox.getSelectedItem().toString();

            ArrayList<PairDouble> myList = Vector.initializeVector(method, query);
            String result = "";
            if (myList.isEmpty()) {
                vectorResultTextArea.setText("No results found");
            } else {
                if (topKTextField.getText().equals("")) {
                    for (PairDouble temp : myList) {
                        result = result + temp.getId() + " : " + temp.getWeight() + "\n";
                    }
                } else {
                    int k = Integer.parseInt(topKTextField.getText());
                    int i = 0;
                    for (PairDouble temp : myList) {
                        if (i < k) {
                            result = result + temp.getId() + " : " + temp.getWeight() + "\n";
                        } else {
                            break;
                        }
                        i++;
                    }
                }
                vectorResultTextArea.setText(result);
            }
        }

    }//GEN-LAST:event_vectorSearchButtonActionPerformed

    private void editCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCollectionButtonActionPerformed
        boolORvectorDialog.setVisible(false);
        editCollectionWindow.setVisible(true);
        String[] myList = Aganaktish.getTxt();
        deleteSelectedList.setListData(myList);
    }//GEN-LAST:event_editCollectionButtonActionPerformed

    private void addTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtButtonActionPerformed
        try {
            if (addtxtSourcePathTextField.getText().equals("")) {
                addTxtWarning.setText("Please insert path");
            } else {
                CollectionClass.addToCollection(addtxtSourcePathTextField.getText());
                addTxtWarning.setText("Item(s) have been added");
                String[] nameList = Aganaktish.getTxt();
                deleteSelectedList.setListData(nameList);
            }
            //update dropbox

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addTxtButtonActionPerformed

    private void deleteTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTxtButtonActionPerformed
        Object[] myList = deleteSelectedList.getSelectedValues();
        if (myList.length == 0) {
            addTxtWarning.setText("Please select and item");
        } else {
            for (Object temp : myList) {
                try {
                    CollectionClass.deleteTxt(temp.toString());
                    addTxtWarning.setText("Item has been deleted");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String[] nameList = Aganaktish.getTxt();
            deleteSelectedList.setListData(nameList);
        }
    }//GEN-LAST:event_deleteTxtButtonActionPerformed

    private void editGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGoBackButtonActionPerformed
        boolORvectorDialog.setVisible(true);
        editCollectionWindow.setVisible(false);
    }//GEN-LAST:event_editGoBackButtonActionPerformed

    private void removeCommonWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCommonWordsButtonActionPerformed
        if (commonPercentageTextField.getText().equals("")) {
            addTxtWarning.setText("Incert percentage");
        } else {
            int percentage = Integer.parseInt(commonPercentageTextField.getText());
            Catalog.removeCommon(percentage);
            addTxtWarning.setText("Common words removed");
        }
    }//GEN-LAST:event_removeCommonWordsButtonActionPerformed

    private void recallCalcCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallCalcCancelButtonActionPerformed
        recallResultTextArea.setText("");
        recallTopKTextField.setText("");
        precisionCalcWindow.setVisible(false);
        boolORvectorDialog.setVisible(true);
    }//GEN-LAST:event_recallCalcCancelButtonActionPerformed

    private void useRecallCalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useRecallCalcButtonActionPerformed

        File myFile = new File(Aganaktish.collectionPath + "\\query\\");
        if (!myFile.exists()) {
            boolORvectorWarningLabel.setText("No queries in this collection");
        } else {
            boolORvectorDialog.setVisible(false);
            precisionCalcWindow.setVisible(true);
        }
    }//GEN-LAST:event_useRecallCalcButtonActionPerformed

    private void recallCalcStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallCalcStartButtonActionPerformed
        String pathquery = Aganaktish.collectionPath + "\\query\\query.txt";
        String pathRel = Aganaktish.collectionPath + "\\query\\relevant.txt";
        int k;
        if (recallTopKTextField.getText().equals("")) {
            k = 0;
        } else {
            k = Integer.parseInt(recallTopKTextField.getText());
        }
        TreeMap<Integer, ArrayList<PairDouble>> myQueryResults;
        TreeMap<Integer, ArrayList<String>> myRelevantResults;
        TreeMap<Integer, double[]> recalpress;
        double sumRecall=0, sumPrecision=0;
        try {
            myQueryResults = Aganaktish.runqueries(pathquery, recallCalcMethodComboBox.getSelectedItem().toString(), k);
            myRelevantResults = Aganaktish.getRelevant(pathRel);
            recalpress = Aganaktish.calculateStats(myQueryResults, myRelevantResults);
            String result="";
            
            Set set= myQueryResults.entrySet();
            Iterator itr= set.iterator();
            
            
            while(itr.hasNext())
            {   
                Map.Entry me= (Map.Entry) itr.next();
                
                int key= (Integer)me.getKey();
                double[] statsTemp=(double[])recalpress.get(key);
                double recall=(Double)statsTemp[0];
                double precision=(Double)statsTemp[1];
                result=result+"query ID: "+key+ " Recall: "+recall+" precision: "+ precision+"\n\n";
                sumRecall=sumRecall +recall;
                sumPrecision= sumPrecision+  precision;
                ArrayList<PairDouble> weightList=myQueryResults.get(key);
                for(PairDouble tempPair:weightList)
                {
                    result=result+tempPair.getId()+"  "+tempPair.getWeight()+"\n";
                }
                
                result=result+"\n------------------\n\n";
                
            }
            result=result+"Recall average: "+sumRecall/myRelevantResults.size()+"\n";
            result=result+"Precision average: "+sumPrecision/myRelevantResults.size()+"\n";
            
            recallResultTextArea.setText(result);
            
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }




    }//GEN-LAST:event_recallCalcStartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxtButton;
    private javax.swing.JLabel addTxtWarning;
    private javax.swing.JTextField addtxtSourcePathTextField;
    private javax.swing.JDialog boolORvectorDialog;
    private javax.swing.JLabel boolORvectorWarningLabel;
    private javax.swing.JButton booleanCancelButton;
    private javax.swing.JTextArea booleanResultTextArea;
    private javax.swing.JButton booleanSearchButton;
    private javax.swing.JLabel booleanWarning;
    private javax.swing.JDialog booleanWindow;
    private javax.swing.JTextField commonPercentageTextField;
    private javax.swing.JButton createCollectionButton;
    private javax.swing.JDialog createCollectionDialog;
    private javax.swing.JButton createOkCollectionButton;
    private javax.swing.JLabel currentCollectionLabel;
    private javax.swing.JList deleteSelectedList;
    private javax.swing.JButton deleteTxtButton;
    private javax.swing.JButton dialogCancelButton;
    private javax.swing.JButton dialogOkButton;
    private javax.swing.JButton editCollectionButton;
    private javax.swing.JDialog editCollectionWindow;
    private javax.swing.JButton editGoBackButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton openCollectionButton;
    private javax.swing.JButton openCollectionCancelButton;
    private javax.swing.JTextField pathTxtField;
    private javax.swing.JDialog precisionCalcWindow;
    private javax.swing.JTextField queryBoolTextField;
    private javax.swing.JTextField queryVectorTextField;
    private javax.swing.JButton recallCalcCancelButton;
    private javax.swing.JComboBox recallCalcMethodComboBox;
    private javax.swing.JButton recallCalcStartButton;
    private javax.swing.JTextArea recallResultTextArea;
    private javax.swing.JTextField recallTopKTextField;
    private javax.swing.JButton removeCommonWordsButton;
    private javax.swing.JComboBox selectCollectionBox;
    private javax.swing.JDialog selectCollectionDialog;
    private javax.swing.JTextField topKTextField;
    private javax.swing.JButton useBooleanButton;
    private javax.swing.JButton useRecallCalcButton;
    private javax.swing.JButton vectorCancelButton;
    private javax.swing.JComboBox vectorMethodComboBox;
    private javax.swing.JTextArea vectorResultTextArea;
    private javax.swing.JButton vectorSearchButton;
    private javax.swing.JLabel vectorWarning;
    private javax.swing.JDialog vectorWindow;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
